name: api_bloc
description: Flutter widgets that simplify the BLoC pattern implementation for REST APIs within an MVC architecture, significantly reducing boilerplate code.
version: 3.0.1
homepage: https://inidia.app
repository: https://github.com/Nialixus/api_bloc.git
issue_tracker: https://github.com/Nialixus/api_bloc/issues
funding:
  - https://ko-fi.com/nialixus
screenshots:
  - description: 'API Bloc Logo'
    path: logo.png
topics:
  - bloc
  - rest-api
  - mvc
  - api

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  args: ^2.5.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  coverage: ^1.8.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
