name: api_bloc
description: Flutter widgets designed to simplify the implementation of the BLoC pattern for REST APIs within an MVC architecture. Significantly reduces boilerplate code by automating BLoC pattern and test generation for handling REST API interactions.
version: 3.0.0
homepage: https://inidia.app
repository: https://github.com/Nialixus/api_bloc.git
issue_tracker: https://github.com/Nialixus/api_bloc/issues
funding:
  - https://ko-fi.com/nialixus
screenshots:
  - description: 'API Bloc Logo'
    path: logo.png
topics:
  - flutter
  - bloc
  - business-logic
  - rest-api
  - mvc
  - state-management
  - api-integration
  - boilerplate-reduction
  - code-generation
  - dart

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  args: ^2.5.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  coverage: ^1.8.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
