name: api_bloc
description: Significantly reducing boilerplate code of BLoC pattern to efficiently handle API interactions.
version: 1.8.0
homepage: https://github.com/Nialixus/api_bloc.git
repository: https://github.com/Nialixus/api_bloc.git
issue_tracker: https://github.com/Nialixus/api_bloc/issues
funding: 
  - https://www.buymeacoffee.com/nialixus
screenshots:
  - description: 'API Bloc Logo'
    path: example/logo.png
topics:
  - bloc
  - api

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  args: ^2.4.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter: null